all:
	$(MAKE) -C ..

newton:
	$(MAKE) -C .. newton

chord:
	$(MAKE) -C .. chord

test:
	$(MAKE) -C .. test

report:
	$(MAKE) -C .. report

clean:
	$(MAKE) -C .. clean

.PHONY: all newton chord test report clean
